# Generated by Django 3.0.5 on 2020-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
